universe=docker
docker_image = pangyuteng/dlstp:umamba-v0.0.1
docker_pull_policy = always

executable = train.sh
transfer_input_files = train.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = log/$(cluster).$(process).out
error = log/$(cluster).$(process).err
log = log/$(cluster).$(process).log

request_cpus = 2
request_gpus = 1
request_memory = 40GB
request_disk = 1024MB

requirements = (OpSys == "LINUX" && Arch == "X86_64" && GPUMEM > 40000)

+DevShmSize = 8589934592

max_materialize = 1

arguments = "$(myargs)"
queue myargs from my.args
